### ISSUE TITLE
Bito cli intermittent not working

### ISSUE THREAD

**Issue by zf0719** [gitbito/CLI#16] opened 2023-05-25 14:50 UTC
```
root@siaphisprb08671:~# bito version
Error: unknown command "version" for "bito"
Run 'bito --help' for usage.
root@siaphisprb08671:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
root@siaphisprb08671:~#
root@siaphisprb08671:~# bito
A new version of Bito CLI was found, updating Bito CLI...

Please re-run "bito" to start using the latest version of Bito CLI.

Note: You can set auto-update to false in the config file to turn off the auto update for Bito CLI.

Sorry, it's us, not you. We had an issue. Please try again.
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
log.Panic({0xc0000dba28?, 0x34?, 0xc0000db9f8?})
        /usr/local/go/src/log/log.go:388 +0x65
BITO/apiclient.processToken({0xc00014c224, 0x12}, {0x0, 0x0}, {0xc000028600, 0x12}, 0x0?)
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/apiclient/user-helper.go:246 +0x465
BITO/apiclient.VerifyEmailConfigurations({0x0, 0x0})
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/apiclient/user-helper.go:211 +0x4cd
BITO/cmd.setConf()
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/cmd/root.go:25 +0x1d
BITO/cmd.glob..func2(0xbf8040?, {0x8a3380?, 0x0?, 0x0?})
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/cmd/root.go:53 +0xae
github.com/spf13/cobra.(*Command).execute(0xbf8040, {0xc000024230, 0x0, 0x0})
        /home/mack3099/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xbf8040)
        /home/mack3099/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/mack3099/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
BITO/cmd.Execute()
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/cmd/root.go:63 +0x25
main.main()
        /mnt/d/BitoWorkSpace/Go Projects/BitoCLI/v4/bitocli/main.go:46 +0xd7
```

**Comment by macky3099** [comment] 2023-05-25 15:45
Hi @zf0719 

Sorry for the issue you faced, you mentioned that the issue is intermittent, so are you still facing it or you face it if you do something specifically? 

The error you see is one of the log getting printed to the screen, ideally it should log to the log file but we will check the missing scenario and fix it.

Thanks!

**Comment by jiahut** [comment] 2023-05-28 07:31
Version 3.3 seems to have become unresponsive during use, resembling a system freeze. I can confirm that internet connectivity is fully operational and the speed is remarkably fast.

**Comment by bitoandy** [comment] 2023-05-28 07:40
Hi @jiahut ,

Thanks for reporting the issue, if possible can you share the log file, if you are using Linux/Mac it should be at ~/.bitoai/etc/logs/bitocli.log you can email it on support@bito.ai or attach it here.

Also were you able to kill and restart bito CLI?

**Comment by bitoandy** [comment] 2023-06-29 16:26
Hi @jiahut ,

Let us know if you are still facing the issue or its resolved now?

**Comment by macky3099** [comment] 2023-09-09 09:30
Hi @jiahut, 

With the version 3.4 of Bito CLI, this should be fixed. Can you please check and confirm if you still facing the same issue?

Thanks!

**Comment by macky3099** [comment] 2023-12-22 05:56
Hi @jiahut, I am closing this issue for now. Please feel free to reopen the issue if you face any issues further. Thanks!

**Closed by macky3099** 2023-12-22 05:56 UTC
Labels: bug
